<?php
/**
 * Plugin Name:       Consentful
 * Plugin URI:        https://github.com/tamarak/consentful
 * Description:        An open-source, universal consent layer that gates all non-essential third-party tags behind visitor consent, adapts to the visitor's jurisdiction, and keeps demonstrable proof of consent.
 * Version:           1.0.0
 * Requires at least: 6.5
 * Requires PHP:      8.1
 * Author:            Tamarak
 * Author URI:        https://tamarak.dev
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       consentful
 * Domain Path:       /languages
 */

declare( strict_types = 1 );

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'CONSENTFUL_VERSION', '1.0.0' );
define( 'CONSENTFUL_FILE', __FILE__ );
// Bump when the Purpose set (consent schema) changes — older cookies are then
// treated as no-consent and the visitor is re-prompted.
define( 'CONSENTFUL_SCHEMA_VERSION', 1 );
// Bump when a jurisdiction Policy changes — triggers re-consent.
define( 'CONSENTFUL_POLICY_VERSION', 1 );
// Bump when the Consent log table schema changes — triggers a dbDelta migration.
define( 'CONSENTFUL_DB_VERSION', 1 );
define( 'CONSENTFUL_OPTION', 'consentful_settings' );
define( 'CONSENTFUL_COOKIE', 'consentful' );

// Composer's PSR-4 autoloader — generated by `composer install` in development
// and shipped in the distributable (built with `--no-dev --optimize-autoloader`).
// The plugin has no runtime dependencies, so vendor/ carries only the autoloader.
$consentful_autoload = __DIR__ . '/vendor/autoload.php';
if ( ! is_readable( $consentful_autoload ) ) {
	return;
}
require $consentful_autoload;

// Create the Consent log table, ensure the record salt, and schedule the retention purge
// on activation. The boot-time upgrade check covers must-use / symlinked dev installs
// where this hook never fires. Deactivation clears the scheduled purge.
if ( class_exists( \Consentful\Activator::class ) ) {
	register_activation_hook( CONSENTFUL_FILE, array( '\\Consentful\\Activator', 'activate' ) );
}
if ( class_exists( \Consentful\Deactivator::class ) ) {
	register_deactivation_hook( CONSENTFUL_FILE, array( '\\Consentful\\Deactivator', 'deactivate' ) );
}

// Defer boot to plugins_loaded so any developer hook callbacks (consentful_purposes,
// _adapters, _tags, _sink) added at their own plugin's include time are in place.
add_action(
	'plugins_loaded',
	static function (): void {
		if ( class_exists( \Consentful\Plugin::class ) ) {
			\Consentful\Plugin::instance()->boot();
		}
	}
);
